"""Prazo para receber o comprovante de entrega, contado em dias úteis a
partir da data de entrega, conforme a distância (em linha reta) entre
Carpina-PE (origem) e a cidade de destino:

    até  50 km ->  2 dias úteis
    até 100 km ->  4 dias úteis
    até 200 km ->  6 dias úteis
    acima      -> 10 dias úteis

A contagem dos dias úteis e a faixa do alerta (No prazo / Alerta / Vencido /
Crítico) são feitas no navegador (static/comprovantes.js), porque dependem
da data de hoje.

`CIDADES_ATE_200KM` foi gerado a partir da base de municípios do IBGE
(github.com/kelvins/municipios-brasileiros) -- só as cidades até 200 km de
Carpina; qualquer outra cidade (ou nome que não bata) fica com 10 dias.
"""

import re
import unicodedata

ORIGEM = "Carpina-PE"

FAIXAS = ((50, 2), (100, 4), (200, 6))
PRAZO_ACIMA = 10


def normalizar_cidade(nome) -> str:
    texto = unicodedata.normalize("NFD", str(nome or ""))
    texto = "".join(c for c in texto if unicodedata.category(c) != "Mn")
    return re.sub(r"[^A-Z0-9]+", " ", texto.upper()).strip()


def prazo_comprovante(cidade, uf) -> tuple[int, int | None]:
    """(dias úteis de prazo, distância em km -- `None` se a cidade não está
    a até 200 km ou o nome não foi reconhecido)."""
    km = CIDADES_ATE_200KM.get((str(uf or "").strip().upper(), normalizar_cidade(cidade)))
    if km is None:
        return PRAZO_ACIMA, None
    for limite, dias in FAIXAS:
        if km <= limite:
            return dias, km
    return PRAZO_ACIMA, km


# (UF, nome normalizado) -> distância de Carpina em km, linha reta.
CIDADES_ATE_200KM = {
    ("AL", "BARRA DE SANTO ANTONIO"): 175,
    ("AL", "BRANQUINHA"): 176,
    ("AL", "CAJUEIRO"): 199,
    ("AL", "CAMPESTRE"): 117,
    ("AL", "CAPELA"): 197,
    ("AL", "CHA PRETA"): 195,
    ("AL", "COLONIA LEOPOLDINA"): 130,
    ("AL", "FLEXEIRAS"): 167,
    ("AL", "IBATEGUARA"): 147,
    ("AL", "JACUIPE"): 113,
    ("AL", "JAPARATINGA"): 138,
    ("AL", "JOAQUIM GOMES"): 153,
    ("AL", "JUNDIA"): 126,
    ("AL", "MARAGOGI"): 129,
    ("AL", "MATRIZ DE CAMARAGIBE"): 149,
    ("AL", "MESSIAS"): 184,
    ("AL", "MURICI"): 179,
    ("AL", "NOVO LINO"): 130,
    ("AL", "PARIPUEIRA"): 183,
    ("AL", "PASSO DE CAMARAGIBE"): 158,
    ("AL", "PORTO CALVO"): 135,
    ("AL", "PORTO DE PEDRAS"): 146,
    ("AL", "RIO LARGO"): 193,
    ("AL", "SANTANA DO MUNDAU"): 182,
    ("AL", "SAO JOSE DA LAJE"): 157,
    ("AL", "SAO LUIS DO QUITUNDE"): 167,
    ("AL", "SAO MIGUEL DOS MILAGRES"): 158,
    ("AL", "UNIAO DOS PALMARES"): 169,
    ("PB", "ALAGOA GRANDE"): 98,
    ("PB", "ALAGOA NOVA"): 104,
    ("PB", "ALAGOINHA"): 105,
    ("PB", "ALCANTIL"): 89,
    ("PB", "ALGODAO DE JANDAIRA"): 135,
    ("PB", "ALHANDRA"): 60,
    ("PB", "ARACAGI"): 112,
    ("PB", "ARARA"): 126,
    ("PB", "ARARUNA"): 154,
    ("PB", "AREIA"): 110,
    ("PB", "AREIAL"): 116,
    ("PB", "AROEIRAS"): 60,
    ("PB", "ASSUNCAO"): 184,
    ("PB", "BAIA DA TRAICAO"): 133,
    ("PB", "BANANEIRAS"): 129,
    ("PB", "BARAUNA"): 175,
    ("PB", "BARRA DE SANTA ROSA"): 154,
    ("PB", "BARRA DE SANTANA"): 89,
    ("PB", "BARRA DE SAO MIGUEL"): 118,
    ("PB", "BAYEUX"): 88,
    ("PB", "BELEM"): 126,
    ("PB", "BOA VISTA"): 126,
    ("PB", "BOQUEIRAO"): 105,
    ("PB", "BORBOREMA"): 123,
    ("PB", "CAAPORA"): 53,
    ("PB", "CABACEIRAS"): 121,
    ("PB", "CABEDELO"): 106,
    ("PB", "CACIMBA DE DENTRO"): 146,
    ("PB", "CAICARA"): 138,
    ("PB", "CALDAS BRANDAO"): 83,
    ("PB", "CAMALAU"): 173,
    ("PB", "CAMPINA GRANDE"): 98,
    ("PB", "CAPIM"): 104,
    ("PB", "CARAUBAS"): 137,
    ("PB", "CASSERENGUE"): 134,
    ("PB", "CATURITE"): 98,
    ("PB", "CONDE"): 76,
    ("PB", "CONGO"): 155,
    ("PB", "COXIXOLA"): 151,
    ("PB", "CRUZ DO ESPIRITO SANTO"): 81,
    ("PB", "CUBATI"): 164,
    ("PB", "CUITE"): 182,
    ("PB", "CUITE DE MAMANGUAPE"): 104,
    ("PB", "CUITEGI"): 110,
    ("PB", "CURRAL DE CIMA"): 125,
    ("PB", "DAMIAO"): 153,
    ("PB", "DONA INES"): 143,
    ("PB", "DUAS ESTRADAS"): 130,
    ("PB", "ESPERANCA"): 113,
    ("PB", "FAGUNDES"): 82,
    ("PB", "GADO BRAVO"): 66,
    ("PB", "GUARABIRA"): 114,
    ("PB", "GURINHEM"): 83,
    ("PB", "GURJAO"): 152,
    ("PB", "INGA"): 74,
    ("PB", "ITABAIANA"): 58,
    ("PB", "ITAPOROROCA"): 114,
    ("PB", "ITATUBA"): 67,
    ("PB", "JACARAU"): 137,
    ("PB", "JOAO PESSOA"): 92,
    ("PB", "JUAREZ TAVORA"): 83,
    ("PB", "JUAZEIRINHO"): 170,
    ("PB", "JUNCO DO SERIDO"): 187,
    ("PB", "JURIPIRANGA"): 54,
    ("PB", "LAGOA DE DENTRO"): 131,
    ("PB", "LAGOA SECA"): 101,
    ("PB", "LIVRAMENTO"): 194,
    ("PB", "LOGRADOURO"): 139,
    ("PB", "LUCENA"): 113,
    ("PB", "MAMANGUAPE"): 113,
    ("PB", "MARCACAO"): 123,
    ("PB", "MARI"): 88,
    ("PB", "MASSARANDUBA"): 94,
    ("PB", "MATARACA"): 141,
    ("PB", "MATINHAS"): 98,
    ("PB", "MOGEIRO"): 67,
    ("PB", "MONTADAS"): 115,
    ("PB", "MULUNGU"): 94,
    ("PB", "NATUBA"): 41,
    ("PB", "NOVA FLORESTA"): 187,
    ("PB", "NOVA PALMEIRA"): 184,
    ("PB", "OLIVEDOS"): 145,
    ("PB", "PARARI"): 166,
    ("PB", "PEDRA LAVRADA"): 182,
    ("PB", "PEDRAS DE FOGO"): 53,
    ("PB", "PEDRO REGIS"): 135,
    ("PB", "PICUI"): 192,
    ("PB", "PILAR"): 65,
    ("PB", "PILOES"): 116,
    ("PB", "PILOEZINHOS"): 116,
    ("PB", "PIRPIRITUBA"): 121,
    ("PB", "PITIMBU"): 64,
    ("PB", "POCINHOS"): 125,
    ("PB", "PUXINANA"): 109,
    ("PB", "QUEIMADAS"): 91,
    ("PB", "REMIGIO"): 117,
    ("PB", "RIACHAO"): 152,
    ("PB", "RIACHAO DO BACAMARTE"): 80,
    ("PB", "RIACHAO DO POCO"): 78,
    ("PB", "RIACHO DE SANTO ANTONIO"): 101,
    ("PB", "RIO TINTO"): 117,
    ("PB", "SALGADINHO"): 194,
    ("PB", "SALGADO DE SAO FELIX"): 58,
    ("PB", "SANTA CECILIA"): 70,
    ("PB", "SANTA RITA"): 87,
    ("PB", "SANTO ANDRE"): 166,
    ("PB", "SAO DOMINGOS DO CARIRI"): 133,
    ("PB", "SAO JOAO DO CARIRI"): 151,
    ("PB", "SAO JOAO DO TIGRE"): 178,
    ("PB", "SAO JOSE DOS CORDEIROS"): 179,
    ("PB", "SAO JOSE DOS RAMOS"): 67,
    ("PB", "SAO MIGUEL DE TAIPU"): 67,
    ("PB", "SAO SEBASTIAO DE LAGOA DE ROCA"): 106,
    ("PB", "SAO SEBASTIAO DO UMBUZEIRO"): 197,
    ("PB", "SAO VICENTE DO SERIDO"): 169,
    ("PB", "SAPE"): 84,
    ("PB", "SERRA BRANCA"): 161,
    ("PB", "SERRA DA RAIZ"): 131,
    ("PB", "SERRA REDONDA"): 87,
    ("PB", "SERRARIA"): 122,
    ("PB", "SERTAOZINHO"): 123,
    ("PB", "SOBRADO"): 78,
    ("PB", "SOLANEA"): 130,
    ("PB", "SOLEDADE"): 151,
    ("PB", "SOSSEGO"): 163,
    ("PB", "SUME"): 181,
    ("PB", "TACIMA"): 157,
    ("PB", "TAPEROA"): 187,
    ("PB", "TENORIO"): 182,
    ("PB", "UMBUZEIRO"): 48,
    ("PE", "ABREU E LIMA"): 39,
    ("PE", "AGRESTINA"): 102,
    ("PE", "AGUA PRETA"): 100,
    ("PE", "ALAGOINHA"): 182,
    ("PE", "ALIANCA"): 27,
    ("PE", "ALTINHO"): 114,
    ("PE", "AMARAJI"): 63,
    ("PE", "ANGELIM"): 162,
    ("PE", "ARACOIABA"): 20,
    ("PE", "BARRA DE GUABIRABA"): 78,
    ("PE", "BARREIROS"): 108,
    ("PE", "BELEM DE MARIA"): 108,
    ("PE", "BELO JARDIM"): 140,
    ("PE", "BEZERROS"): 74,
    ("PE", "BOM JARDIM"): 36,
    ("PE", "BONITO"): 87,
    ("PE", "BREJAO"): 196,
    ("PE", "BREJO DA MADRE DE DEUS"): 128,
    ("PE", "BUENOS AIRES"): 15,
    ("PE", "CABO DE SANTO AGOSTINHO"): 55,
    ("PE", "CACHOEIRINHA"): 130,
    ("PE", "CAETES"): 184,
    ("PE", "CALCADO"): 155,
    ("PE", "CAMARAGIBE"): 36,
    ("PE", "CAMOCIM DE SAO FELIX"): 80,
    ("PE", "CAMUTANGA"): 49,
    ("PE", "CANHOTINHO"): 155,
    ("PE", "CAPOEIRAS"): 181,
    ("PE", "CARPINA"): 0,
    ("PE", "CARUARU"): 93,
    ("PE", "CASINHAS"): 53,
    ("PE", "CATENDE"): 105,
    ("PE", "CHA DE ALEGRIA"): 19,
    ("PE", "CHA GRANDE"): 49,
    ("PE", "CONDADO"): 33,
    ("PE", "CORRENTES"): 185,
    ("PE", "CORTES"): 77,
    ("PE", "CUMARU"): 52,
    ("PE", "CUPIRA"): 116,
    ("PE", "ESCADA"): 57,
    ("PE", "FEIRA NOVA"): 18,
    ("PE", "FERREIROS"): 44,
    ("PE", "FREI MIGUELINHO"): 73,
    ("PE", "GAMELEIRA"): 83,
    ("PE", "GARANHUNS"): 179,
    ("PE", "GLORIA DO GOITA"): 18,
    ("PE", "GOIANA"): 42,
    ("PE", "GRAVATA"): 54,
    ("PE", "IBIRAJUBA"): 131,
    ("PE", "IGARASSU"): 39,
    ("PE", "ILHA DE ITAMARACA"): 48,
    ("PE", "IPOJUCA"): 64,
    ("PE", "ITAMBE"): 51,
    ("PE", "ITAPISSUMA"): 40,
    ("PE", "ITAQUITINGA"): 26,
    ("PE", "JABOATAO DOS GUARARAPES"): 40,
    ("PE", "JAQUEIRA"): 115,
    ("PE", "JATAUBA"): 138,
    ("PE", "JOAO ALFREDO"): 36,
    ("PE", "JOAQUIM NABUCO"): 92,
    ("PE", "JUCATI"): 166,
    ("PE", "JUPI"): 160,
    ("PE", "JUREMA"): 136,
    ("PE", "LAGOA DE ITAENGA"): 10,
    ("PE", "LAGOA DO CARRO"): 7,
    ("PE", "LAGOA DO OURO"): 195,
    ("PE", "LAGOA DOS GATOS"): 116,
    ("PE", "LAJEDO"): 149,
    ("PE", "LIMOEIRO"): 21,
    ("PE", "MACAPARANA"): 39,
    ("PE", "MACHADOS"): 34,
    ("PE", "MARAIAL"): 123,
    ("PE", "MORENO"): 35,
    ("PE", "NAZARE DA MATA"): 12,
    ("PE", "OLINDA"): 47,
    ("PE", "OROBO"): 40,
    ("PE", "PALMARES"): 100,
    ("PE", "PALMEIRINA"): 175,
    ("PE", "PANELAS"): 123,
    ("PE", "PARANATAMA"): 195,
    ("PE", "PASSIRA"): 40,
    ("PE", "PAUDALHO"): 11,
    ("PE", "PAULISTA"): 43,
    ("PE", "PEDRA"): 199,
    ("PE", "PESQUEIRA"): 169,
    ("PE", "POCAO"): 165,
    ("PE", "POMBOS"): 36,
    ("PE", "PRIMAVERA"): 55,
    ("PE", "QUIPAPA"): 136,
    ("PE", "RECIFE"): 47,
    ("PE", "RIACHO DAS ALMAS"): 75,
    ("PE", "RIBEIRAO"): 75,
    ("PE", "RIO FORMOSO"): 91,
    ("PE", "SAIRE"): 73,
    ("PE", "SALGADINHO"): 45,
    ("PE", "SANHARO"): 156,
    ("PE", "SANTA CRUZ DO CAPIBARIBE"): 106,
    ("PE", "SANTA MARIA DO CAMBUCA"): 71,
    ("PE", "SAO BENEDITO DO SUL"): 132,
    ("PE", "SAO BENTO DO UNA"): 152,
    ("PE", "SAO CAETANO"): 126,
    ("PE", "SAO JOAO"): 168,
    ("PE", "SAO JOAQUIM DO MONTE"): 89,
    ("PE", "SAO JOSE DA COROA GRANDE"): 117,
    ("PE", "SAO LOURENCO DA MATA"): 32,
    ("PE", "SAO VICENTE FERRER"): 38,
    ("PE", "SIRINHAEM"): 84,
    ("PE", "SURUBIM"): 55,
    ("PE", "TACAIMBO"): 126,
    ("PE", "TAMANDARE"): 103,
    ("PE", "TAQUARITINGA DO NORTE"): 87,
    ("PE", "TIMBAUBA"): 38,
    ("PE", "TORITAMA"): 91,
    ("PE", "TRACUNHAEM"): 5,
    ("PE", "VENTUROSA"): 196,
    ("PE", "VERTENTE DO LERIO"): 66,
    ("PE", "VERTENTES"): 79,
    ("PE", "VICENCIA"): 22,
    ("PE", "VITORIA DE SANTO ANTAO"): 32,
    ("PE", "XEXEU"): 114,
    ("RN", "ARES"): 185,
    ("RN", "BAIA FORMOSA"): 166,
    ("RN", "BREJINHO"): 185,
    ("RN", "CANGUARETAMA"): 164,
    ("RN", "CORONEL EZEQUIEL"): 196,
    ("RN", "EQUADOR"): 191,
    ("RN", "ESPIRITO SANTO"): 168,
    ("RN", "GOIANINHA"): 176,
    ("RN", "JACANA"): 190,
    ("RN", "JANUARIO CICCO BOA SAUDE"): 191,
    ("RN", "JAPI"): 171,
    ("RN", "JUNDIA"): 176,
    ("RN", "LAGOA D ANTA"): 166,
    ("RN", "LAGOA DE PEDRAS"): 189,
    ("RN", "LAGOA SALGADA"): 193,
    ("RN", "MONTANHAS"): 151,
    ("RN", "MONTE ALEGRE"): 198,
    ("RN", "MONTE DAS GAMELEIRAS"): 167,
    ("RN", "NISIA FLORESTA"): 195,
    ("RN", "NOVA CRUZ"): 154,
    ("RN", "PASSA E FICA"): 163,
    ("RN", "PASSAGEM"): 175,
    ("RN", "PEDRO VELHO"): 157,
    ("RN", "SANTA CRUZ"): 199,
    ("RN", "SANTO ANTONIO"): 172,
    ("RN", "SAO BENTO DO TRAIRI"): 191,
    ("RN", "SAO JOSE DE MIPIBU"): 197,
    ("RN", "SAO JOSE DO CAMPESTRE"): 178,
    ("RN", "SENADOR GEORGINO AVELINO"): 188,
    ("RN", "SERRA DE SAO BENTO"): 166,
    ("RN", "SERRINHA"): 176,
    ("RN", "TANGARA"): 193,
    ("RN", "TIBAU DO SUL"): 185,
    ("RN", "VARZEA"): 167,
    ("RN", "VILA FLOR"): 172,
}
